### ISSUE TITLE
Audit public lookup tables

### ISSUE THREAD

**Issue by kriskowal** [uber/thriftrw#35]
Should look like this in the end:

- `spec.structs.{structName}` struct constructor
- `spec.services.{serviceName}.{functionName}.{args,result}` arg and result constructors
- `spec.enums.{enumName}.{enumKey}` enum values
- `spec.consts.{constName}` const values
- `spec.typedefs.{typedefName}` type spec for typedef
- `spec.types` will continue to be a combined index of structs from struct and function specs used by `getType` and `getTypeResult` for thriftify compatibility.

**Comment by kriskowal** [comment]
I’m favoring a simpler interface.

Dynamic:

- `spec.getType(name)` returns the spec for a given type (struct, exception, typedef, union) or throws
- `spec.getTypeResult(name)` returns the result for spec for a given type (struct, exception, typedef, union)

Flat lookup for statics. Thrift IDL has a single name space for all these, so I don’t see a need to provide a taxonomy. Emphasis that this interface is for coding directly against the types provided in the Thrift IDL checked into your project.

- `spec.{structName}` struct constructor
- `spec.{exceptionName}` exception constructor
- `spec.{unionName}` union constructor
- `spec.{typedefName}` surface of referenced type
    - constructor for struct, exception, union
    - constructor-like functions for base types and compound types including Array for lists
- `spec.{serviceName}.{functionName}.{args,result}` arg and result constructors
- `spec.{enumName}.{name}` "interned" string for enum name
- `spec.{constName}` const values

**Comment by kriskowal** [comment]
Opinions welcome from stake-holders, calling out the ones I know might care off-hand: @leizha @Willyham @malandrew @raynos @jcorbin @ShanniLi @abhinav @breerly. Simple question: flat or taxonomy. I’ll worry about the specific colors.

**Comment by Raynos** [comment]
Less is more.

The public interface for `spec` mostly concerns itself with `encodeResult` `decodeResult`, `encodeArgs`, `decodeArgs`

You have a first class typed error integration so maybe `spec.errors.{errorName}`. Note I said `spec.errors` and not `spec.structs` or `spec.exceptions`. The main feature here is exposing typed error contructors; not exposing thriftrw internals.

I would recommend keeping the internals in an internal dictionary somewhere.

**Comment by abhinav** [comment]
+1 on the simpler interface

**Comment by Willyham** [comment]
I have a slight preference for the taxonomy because it won't always be obvious what the type of the entity is in the current context.

When you're reading/writing a thrift spec, you have the context because it's the preceding keyword:
```
struct Foo
enum Foo
exception Foo
```

But in the code, reading 
```
spec.struct.Foo
spec.exception.Foo
``` 
Is totally clear, whereas 
```
spec.Foo
```
Is ambiguous.

I don't see any downside to the taxonomy if the implementation is the same. More keystrokes is **not** a good reason.

**Comment by abhinav** [comment]
Couple reasons to go with the simplified approach:

- They will share the same namespace, which is the same as what Thrift does.
- There's no difference in how you consume a struct versus how you instantiate a union or exception, so you're not gaining any value:

        spec.struct.Foo({attr1: 'a', attr2: 'b'})
        spec.union.Foo({attr1: 'a'})
        spec.exception.Foo({attr1: 'a', attr2: 'b'})

  (Besides the obvious difference that unions can have only one value; these are things you're expected to know about the Thrift service you're consuming anyway.)

Is the motivation for the taxonomy so that you can do runtime introspection and add more functionality around it?

**Comment by Willyham** [comment]
We should be thinking about the people reading the code, not just writing it. For people less familiar with the service, they'd need to continually search the thrift spec for the type every time it was used.

Now that you bring it up, introspection around exceptions would definitely be useful. We're already explicitly differentiating all typed Errors and  Exceptions, marking the exceptions explicitly:
```
var NotFoundException = TypedError({
  type: 'not.found',
  message: '{entity} {identifier} Not Found',
  typeName: 'notFound',
  isException: true,
  entity: null,
  identifier: null
});
```
We do this so that we can have a generic error handler on our endpoints which will catch errors thrown and either `callback(err)` or `callback(null, { ok: false, body: err, typeName: err.typeName } )`. This makes the handlers a lot simpler.

I haven't found a use case for any other of the types just yet (though enums might be useful too).
